# travis config, based on https://github.com/craigcitro/r-travis

language: c
script: ./travis-tool.sh run_tests
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh github_package hadley/testthat
  - ./travis-tool.sh github_package hadley/assertthat
  - ./travis-tool.sh github_package berndbischl/BBmisc
  - ./travis-tool.sh github_package berndbischl/parallelMap
  - ./travis-tool.sh github_package berndbischl/ParamHelpers
  - ./travis-tool.sh install_deps
branches:
  except:
   - /-expt$/
after_failure:
  - cat SVMBridge.Rcheck/00install.out
  - cat SVMBridge.Rcheck/00check.log
  - cat SVMBridge.Rcheck/tests/run-all.Rout.fail
notifications:
  email:
    recipients:
      - aydin.demircioglu@ini.rub.de
    on_success: change
    on_failure: always
    