language: r
env:
    global:
        - _R_CHECK_TIMINGS_=0
branches:
    only:
        - master
warnings_are_errors: true
r_check_args: "--as-cran --run-donttest"
apt_packages:
    - r-cran-rjava
r_github_packages:
    - berndbischl/BBmisc
    - berndbischl/parallelMap
    - berndbischl/ParamHelpers
r_binary_packages:
    - ada
    - adabag
    # - bartMachine
    - brnn
    - bst
    - care
    - caret
    - checkmate
    - class
    - clue
    - cluster
    - clusterSim
    - clValid
    - cmaes
    - CoxBoost
    - crs
    - Cubist
    - DiceKriging
    - DiceOptim
    - DiscriMiner
    - deepnet
    - e1071
    - earth
    - elasticnet
    - elmNN
    - emoa
    # - extraTrees
    - fields
    - flare
    - FNN
    - frbs
    - FSelector
    - gbm
    - GenSA
    - ggplot2
    - ggvis
    - glmnet
    - Hmisc
    - irace
    - kernlab
    - kknn
    - klaR
    - knitr
    - kohonen
    - laGP
    - LiblineaR
    - lqa
    - MASS
    - mboost
    - mco
    - mda
    - mlbench
    - modeltools
    - mRMRe
    - neuralnet
    - nnet
    - nodeHarvest
    - pamr
    - party
    - penalized
    - pls
    - plyr
    # - PMCMR
    - pROC
    - randomForest
    - randomForestSRC
    - reshape2
    - RCurl
    - RSNNS
    - rFerns
    - rjson
    - rmarkdown
    - robustbase
    - ROCR
    - rpart
    - rrlda
    - rsm
    - RWeka
    - sda
    - shiny
    - sparsediscrim
    - sparseLDA
    - stepPlr
    - stringi
    - SwarmSVM
    - testthat
    - tgp
    - TH.data
    - XML
before_install:
    - sudo R CMD javareconf
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get -qq update
    - sudo apt-get -qq install gcc-4.8
    - sudo apt-get -qq install g++-4.8
    - sudo apt-get install -qq gfortran-4.8
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-4.8 90
after_success:
    - git checkout master
    - R --no-save <<< 'library("devtools"); document()'
    - git config user.name $GIT_NAME
    - git config user.email $GIT_EMAIL
    - git config credential.helper "store --file=.git/credentials"
    - echo "https://$GH_TOKEN:@github.com" >> .git/credentials
    - git config push.default matching
    - git commit man DESCRIPTION NAMESPACE -m "update auto-generated documentation [ci skip]" || true
    - git push
after_failure:
    - cat ./SVMBridge.Rcheck/tests/testthat.Rout
notifications:
  email:
    recipients:
        - aydin.demircioglu@ini.rub.de
    on_success: change
    on_failure: always
    