---
title: "SVMBridge"
author: "Aydin Demircioglu"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Helpers}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


**SVMBridge** has some helper functions that might be of use outside the SVM context. We give a short list here, for more, please refer to the corresponding documentation.

- **expandTilde**: This will expand a path containing a tilde (=home directory on Unix-like OSs) into a full path, e.g. '~/R' might expand to '/home/user/R' on Unix or '/Users/user/R' on Windows.

- **..**


Notice that the LIBSVM wrapper is the only one that is directly available when loading the **SVMBridge**. The reason for not including other wrappers directly is to reduce dependencies. But as on the other hand other wrappers depend on the functionality of the LIBSVM wrapper to avoid code duplication, LIBSVM is included into the package.

**Warning:** Currently we do not seek completeness. The **SVMBridge** is a classification-only package, so many options e.g. regarding regression are not supported at all. Some other options, although they can be used with classifications, might be missing too. In case you need something, you will need to adapt an existing classifier or simply write your own.

**Note:** For convenience, all the wrappers apart from LIBSVM are nonetheless installed along the package and can be accessed by specifying the correct path. See the introduction for examples on how to do this.


# LIBSVM

LIBSVM is practially the de-facto standard SVM solver. It can be found at http://


# LASVM

LASVM is very similar to LIBSVM wrapper, as both packages use the same parameters and the same model. LASVM has many more options than LIBSVM, as for our purpose we did not need them, for now these are not supported. Please feel free to enhance the wrapper and share the results with us, so we can include these in future versions of **SVMBridge**.


# LLSVM

Part of the BudgetedSVM package, at http://


# Budgeted SGD

Part of the BudgetedSVM package, at http://


# Pegasos

Part of the BudgetedSVM package, at http://


# SVMperf


Currently the package can be found at http://
Note: Please do not mix SVMperf with SVMlight or SVMRank.

SVMperf has many options, so instead of providing all of these as parameter, we decided instead to give the user a choise over several 'configurations'.




# CVM

libCVM, found at http://

# BVM

Though BVM is practially the same software as CVM, sharing models and parameters and executables with CVM, the philosophy of **SVMBridge** is to have a separate wrapper for each method. Thus, though BVM has its own wrapper, all the parameters etc are the same as CVM, so please read the CVM section.


There are several other packages, namely
