---
title: "SVMBridge"
author: "Aydin Demircioglu"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


# Introduction

This introduction gives you a short overview and a  quickstart example of a typical call of an SVM Package with **SVMBridge**to make you familiar with the **SVMBridge**. For much more detailed information see [the next chapter](detailed.Rmd).

The SVMBridge allows to execute any SVM binary package directly within R. For this, it needs three parts:

- A 'wrapper'. This is an R source code file that contains directions on how to execute the SVM, read and write models etc.
- The SVM binaries. These consist of two executables, one for training, one for testing.
- Data. Usually one set for training and one for validating/testing.

In this tutorial, we aim to use the LIBSVM package for a simple SVM classification. Notice that there are already packages like e1071 which allow direct use of LIBSVM within R. Our approach here differs, as any SVM (for classification) can be wrapped, this comes in handy when e.g. you modify/recompile LIBSVM. In this case a simple recompile is enough, there is no need to modify any R package.

 As  said, the **SVMBridge** is just an easy way to call a precompiled SVM package, we first need such an SVM package. We settle with the probably best known SVM solver, LIBSVM. Download the source package from the LIBSVM webpage (currently at http://www.csie.ntu.edu.tw/~cjlin/libsvm/), either as zip/tar or directly from github. Put it into any folder you like. We here assume that you have a software directory and unzipped LIBSVM under 'software/LIBSVM'. If you are using windows, the package should contain already precompiled binaries, in this case you can skip the res of this paragraph. If you use any other OS, you need to compile LIBSVM. For this, go to this directory and call 'make' from the command line (Make sure to have all the necessary c++ packages installed). After successful compilation you will have two binary executables: svm-train and svm-predict. Make sure you can execute them by just calling './svm-train' (an extensive help page should be shown).

The next thing we need is the wrapper (for more details on this and also on how to write your own wrapper, see  [Wrappers](wrappers.md)). The **SVMBridge** comes with several wrappers already, and we will use the LIBSVM wrapper for our purpose. The wrappes can be found in the folder 'wrapper' just below the installation folder of the package.

Before we can use the **SVMBridge**, we need some data. Remember, that the data of a general machine learning problem usually consists of two parts: Training and testing data. The LIBSVM dataset webpage provides many different benchmark data sets (currently at 'http://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/'). To keep things simple, we will use the same data set for testing and training. Download the scaled australian data set (currently at 'http://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary/australian_scale') and put it into a folder. We assume here that you download it to  'data/australian_scale'.

Now,  you can write your first simple R-script:

```splus
# load the SVMBridge
library(SVMBridge)

# add the prepackaged wrapper
addSVMPackage("LIBSVM", wrapperPath =  file.path (path.package("SVMBridge"), "wrapper"))

# let SVMBridge find the compiled/downloaded LIBSVM package.
found = findSVMSoftware (method = 'LIBSVM', searchPath = "./software/LIBSVM")

# use the SVMBridge to train LIBSVM
svmObj =  trainSVM("LIBSVM", trainDataFile = './data/australian_scale', cost = 1, gamma = 1)
```

**Note:** In case something goes wrong, you can add the verbose = TRUE flag to the trainSVM function. Sometimes the paths are wrong, i.e. **SVMBridge** cannot find the LIBSVM executable or the data set.

The ```trainSVM``` function will return an object that contains the trained model and some basic information about the training process, e.g. the training time (including I/O). See  [In Depth Introduction](detailed.md) for more information about the returned SVM object.

Here we print the training time LIBSVM needed and then go ahead and test the model on the test data (as said, for convenience we use the very same training data set for testing, greatly underestimating the generalization error). To do so, we need to pass the trained SVM model to the testSVM routine:

```splus
# print the time needed for training
cat( paste("LIBSVM took", svmObj$trainTime, "seconds to train.\n"))

# use the SVMBridge to test LIBSVM (here on the same data set)
testObj = testSVM(testDataFile = './data/australian_scale', model = svmObj$model)

# print the test error
cat( paste("Test error is ", round(testObj$testError,2), ". Testing took ", round (testObj$testTime,3) , " seconds.\n", sep = ''))
```

Congratulations, you trained your first LIBSVM model via the **SVMBridge**.
