---
title: "SVMBridge"
author: "Aydin Demircioglu"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Wrappers}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


# Wrappers

**SVMBridge** comes with a couple of wrappers for different SVM packages. Here we list these and provide a few details on how to use them.

### WARNING: Not all features for each solver are supported yet!

| | | | |
|-|-|-|-|
|BSGD| Budgeted SGD | m | http://www.dabi.temple.edu/budgetedsvm/
|BVM| Ball Vector Machine | m | http://c2inet.sce.ntu.edu.sg/ivor/cvm.html
|CVM| Core Vector Machine | m | http://c2inet.sce.ntu.edu.sg/ivor/cvm.html
|LASVM |  | b | http://leon.bottou.org/projects/lasvm
|LIBSVM |   | m | https://www.csie.ntu.edu.tw/~cjlin/libsvm/
|LLSVM| Low-rank linearization SVM | b | http://www.dabi.temple.edu/budgetedsvm/
|SVMperf|   | b |  https://www.cs.cornell.edu/people/tj/svm_light/svm_perf.html

**Legend**: m = multiclass, b = binary

**Warning:** Currently we do not seek completeness. The **SVMBridge** is a classification-only package, so many options e.g. regarding regression etc. are currently not supported. Some other options, although they can be used with classifications, might be missing too. In case you are missing something, you will need to adapt an existing classifier or simply write your own from scratch. Either way, please share your results with us, so we can include these in future versions of the **SVMBridge**.


**Note:** For convenience, all the wrappers are installed along the package and can be accessed by specifying the wrapper folder in the path of the installed **SVMBridge**. See the introduction for examples on how to do this.

**Note:** For convenience, all the source code of the prepackaged SVM solvers are also on our github repository. You can also download the versions we used from there: [SVMBridge github repository](github.com/aydindemircioglu/SVMBridge])




## LIBSVM

LIBSVM is practically the de-facto standard SVM solver.
The wrapper supports for now classification and RBF kernel only.



## LASVM

LASVM is very similar to LIBSVM wrapper, as both packages use the same parameters and the same model. LASVM has many more options than LIBSVM, as for our purpose we did not need them, for now these are not supported.



## LLSVM


LLSVM is part of the BudgetedSVM package, see http://www.dabi.temple.edu/budgetedsvm/.


**Note**: The models saved by LLSVM are quite non-standard, as the transformation matrices
have to be saved instead of a list of support vectors. The wrapper includes a simple
reader, which is written in pure R. Therefore, the performance of this wrapper is rather
reduced. In case you need faster model readers/writers, you need to handle it by
yourself.



## Budgeted SGD

BSGD is part of the BudgetedSVM package.

**Note**: The models saved by BSGD are quite non-standard, as the transformation matrices
have to be saved instead of a list of support vectors. The wrapper includes a simple
reader, which is written in pure R. Therefore, the performance of this wrapper is rather
reduced. In case you need faster model readers/writers, you need to handle it by
yourself.


## SVMperf

SVMperf has a great deal of options, so instead of providing all of these as parameter, we decided instead to give the user a choice over several 'configurations'.


**Note**: Please do not mix up SVMperf with SVMlight or SVMRank.

**Note**: The original binaries, when called without or with wrong options, will wait for a key press.



## CVM


**Note**: The source code for CVM cannot be found in the internet anymore.
Therefore we provide a copy of it in our github repository, see above.


## BVM

Though BVM is practially the same software as CVM, sharing models and parameters and executables with CVM, the philosophy of **SVMBridge** is to have a separate wrapper for each method. Thus, though BVM has its own wrapper, all the parameters etc are the same as CVM, so please read the CVM section.

**Note**: The source code for BVM cannot be found in the internet anymore.
Therefore we provide a copy of it in our github repository, see above.
