// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// readSparseData
RcppExport SEXP readSparseData(SEXP filename, SEXP verbose);
RcppExport SEXP SVMBridge_readSparseData(SEXP filenameSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(readSparseData(filename, verbose));
    return __result;
END_RCPP
}
// writeSparseData
RcppExport SEXP writeSparseData(SEXP x, SEXP y, SEXP filename, SEXP verbose);
RcppExport SEXP SVMBridge_writeSparseData(SEXP xSEXP, SEXP ySEXP, SEXP filenameSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(writeSparseData(x, y, filename, verbose));
    return __result;
END_RCPP
}
