// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// readSparseData
List readSparseData(std::string filename, unsigned long skipBytes, bool verbose, bool zeroBased);
RcppExport SEXP SVMBridge_readSparseData(SEXP filenameSEXP, SEXP skipBytesSEXP, SEXP verboseSEXP, SEXP zeroBasedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type skipBytes(skipBytesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type zeroBased(zeroBasedSEXP);
    __result = Rcpp::wrap(readSparseData(filename, skipBytes, verbose, zeroBased));
    return __result;
END_RCPP
}
// writeSparseData
List writeSparseData(std::string filename, NumericMatrix X, NumericMatrix Y, bool append, unsigned long skipBytes, bool verbose, bool zeroBased);
RcppExport SEXP SVMBridge_writeSparseData(SEXP filenameSEXP, SEXP XSEXP, SEXP YSEXP, SEXP appendSEXP, SEXP skipBytesSEXP, SEXP verboseSEXP, SEXP zeroBasedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< bool >::type append(appendSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type skipBytes(skipBytesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type zeroBased(zeroBasedSEXP);
    __result = Rcpp::wrap(writeSparseData(filename, X, Y, append, skipBytes, verbose, zeroBased));
    return __result;
END_RCPP
}
