// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// readSparseData
List readSparseData(std::string filename, bool verbose, bool zeroBased);
RcppExport SEXP SVMBridge_readSparseData(SEXP filenameSEXP, SEXP verboseSEXP, SEXP zeroBasedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type zeroBased(zeroBasedSEXP);
    __result = Rcpp::wrap(readSparseData(filename, verbose, zeroBased));
    return __result;
END_RCPP
}
// writeSparseData
List writeSparseData(std::string filename, NumericMatrix x, NumericVector y, bool verbose, bool zeroBased);
RcppExport SEXP SVMBridge_writeSparseData(SEXP filenameSEXP, SEXP xSEXP, SEXP ySEXP, SEXP verboseSEXP, SEXP zeroBasedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type zeroBased(zeroBasedSEXP);
    __result = Rcpp::wrap(writeSparseData(filename, x, y, verbose, zeroBased));
    return __result;
END_RCPP
}
