# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute several optimization values from a model like primal value
#'
#' @param 	X		input data
#' @param		Y		labels
#' @param		C		regularization value from svm problem
#' @param		gamma	used kernel bandwidth 
#' @param		SV		matrix of support vectors
#' @param		nSV		vector of number of support vectors, needed for the multiclass case
#' @param		sv_coef		alpha of support vectors
#' @param		rho		vector of offset/bias terms
#' @param		label		vector of label mapping
#' @note 		works with LIBSVMlike models only
#' @note		all computations will be done in DENSE format, not sparse!
#' @return		list of optimization values
#' @export
computeOptimizationValues <- function(X, Y, C, gamma, SV, nSV, sv_coef, rho, label, verbose = FALSE) {
    .Call('SVMBridge_computeOptimizationValues', PACKAGE = 'SVMBridge', X, Y, C, gamma, SV, nSV, sv_coef, rho, label, verbose)
}

#' Read a given file in sparse (LIBSVM) format to dense R matrix and R vector.
#'
#' @param 		filename		the filename of the data in sparse file format. The Tilde Character isn't supported for f filename!  
#' @param		verbose		show verbose output?
#' @param		zeroBased	do the indices in the file start with 0, e.g. -1 0:2 1:4 ...?
#' @keywords	IO 
#' @note		this routine is nearly a 1:1 adoptation from the LIBSVM original code.
#' @return		the data is read into an R matrix and an R vector, containing the data
#'					and the labels. note, that these are not in sparse format, but are dense.
#' @examples	
#' \dontrun{
#'		S = readSparseData("../../../SVMBridge/tests/data/australian.train")
#'		print (paste("Data has", nrow(S$X), "points."))
#'		print (paste("Labels are", unique(S$Y), "."))
#'	}
#' @export
readSparseData <- function(filename, skipBytes = 0L, verbose = FALSE, zeroBased = FALSE) {
    .Call('SVMBridge_readSparseData', PACKAGE = 'SVMBridge', filename, skipBytes, verbose, zeroBased)
}

#' Write given (dense) R matrix and R vector in sparse (LIBSVM) format to given file.
#'
#' @param 	filename		the filename to write the given data to
#' @param		verbose		show verbose output?
#' @param		zeroBased	do the indices in the file start with 0, e.g. -1 0:2 1:4 ...?
#' @note		labels can any numeric, they are not converted in any way.
#' @keywords	IO 
#' @return		NULL.
#' @examples	
#'		X = as.matrix(iris[,1:4])
#'		Y = as.matrix(as.numeric(iris[,5]))
#'		writeSparseData ("./australian.data", X, Y)
#' @export
writeSparseData <- function(filename, X, Y, skipBytes = 0L, verbose = FALSE, zeroBased = FALSE) {
    .Call('SVMBridge_writeSparseData', PACKAGE = 'SVMBridge', filename, X, Y, skipBytes, verbose, zeroBased)
}

