# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Read a given file in sparse (LIBSVM) format to dense R matrix and R vector.
#'
#' @param 	filename		the filename of the data in sparse file format
#' @param		verbose		show verbose output?
#' @param		zeroBased	do the indices in the file start with 0, e.g. -1 0:2 1:4 ...?
#' @keywords	IO 
#' @note		this routine is nearly a 1:1 adoptation from the LIBSVM original code.
#' @return		the data is read into an R matrix and an R vector, containing the data
#'					and the labels. note, that these are not in sparse format, but are dense.
#' @examples	
#'					readSpareData ("./australian.data")
#' @export
readSparseData <- function(filename, verbose = FALSE, zeroBased = FALSE) {
    .Call('SVMBridge_readSparseData', PACKAGE = 'SVMBridge', filename, verbose, zeroBased)
}

#' Write given (dense) R matrix and R vector in sparse (LIBSVM) format to given file.
#'
#' @param 	filename		the filename to write the given data to
#' @param		verbose		show verbose output?
#' @param		zeroBased	do the indices in the file start with 0, e.g. -1 0:2 1:4 ...?
#' @note		labels can any numeric, they are not converted in any way.
#' @keywords	IO 
#' @return		NULL.
#' @examples	
#'	X = as.matrix(iris[,1:4])
#'	Y = as.matrix(as.numeric(iris[,5]))
#'	writeSparseData (X, Y, "./australian.data")
#' @export
writeSparseData <- function(filename, X, Y, verbose = FALSE, zeroBased = FALSE) {
    .Call('SVMBridge_writeSparseData', PACKAGE = 'SVMBridge', filename, X, Y, verbose, zeroBased)
}

